provider:
  osx: travis
appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: XQxHmVt1i8vOlhVwH8AFHrCW6tUKdBn20YqRuBSW8KQPpH7D3qyz6RDVdA5YJV8VwtsQ1dUizj93b2VARUAyST8n/TjHL0/LYdZKjHJWRp9HltwBP7DiqAwoqCFIWVJTA6OIjpah9qwUI11R2wbS6jk3zo4sPYCqvuosQbwtTfeUh9iGghKXjdEYyIxzDSd05b7KLQi3XWPg22ZCBbMr+AxV/5CqVS+lvMeDsperyXpIyETDp+53jsdYmBUjPC3dZQX3jw4mbBpP0lyFZQ4897hFhZq2l6646fXug3elQYmZlIVJTeHOup3ws1NKbThpjwY/iH2zbKVg6+coVs11vYraSPbYwFBqp3dklsX7KVInhyERs7rjjR3qTuNI2SGhr3TDv9xhvaJJcP5QW2TYzSa6YUTcFztfyFd0Xmr/rwY10U5F++ah/nrFrbaYwgtX2UsQ0UH5WYxzM5r83da3vyJWplaGpTCOGbV9wu57Q5C9z10NN8mxisvpZYsszbLSz42pyTBFMobyNd4bU+sljJmKZOsk7fxv0bImXKmjKQr29+ZwPGee/zZ1I7kV6RfhQWtJguSk9CjdF7EjZOo82z3cjr2kndAEtjkat8M2OIea4Ux4vsmQpKVllCFXQcjH/3HB3lTyJSo+mHANNHrZr22iPD5R8m+rbJCttdQfzVc=}
conda_forge_output_validation: true
